Feat/cse 285 index data
osu-cass/AP-CSE-API pull request #14
Opened 2018-09-21 20:23 UTC by danvanhorn

# Changes introduced

A new `SearchClient` class that can connect to an `elasticsearch` container. An instance of this class is initialized in the server context and passed through to route in `response.locals`. In the `init/` route the client is used to insert the data into `elasticsearch`, after it is inserted into the db. The function `getClaims()` has been added to dump the data from the into `elasticsearch` , it may not be needed in the future due to architecture decisions although it keeps the data in sync for now.

## Related issue(s):

- CSE-275
- CSE-277
- CSE-285

## Contributor checklist

- [x] Wrote/updated tests for introduced changes
- [ ] ~~Added new stories for created/modified components (if applicable)~~
- [ ] ~~Updated Postman library for created/modified routes (if applicable)~~
- [ ] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [x] Requested review from the SB Reviewers team

## Reviewer checklist

- [x] Assigned yourself to the PR
- [x] Read through the changes in the `Files changed` tab
- [x] Verified that tests were written/modified
- [ ] ~~Verified that stories were written/modified (if applicable)~~
- [x] Verified that Postman was updated (if applicable)
- [x] Checked out the branch and tested changes locally

2018-10-03 00:23 UTC, puregarlic requested changes
Nice work so far, I just want to clear the two items I marked first.

2018-10-03 00:23 UTC, puregarlic commented on src/dal/search/index.ts
> +    this.host = 'es-search:9200';
Is there a particular reason why you didn't use the same paradigm as the Mongo constructer and pass the host in as a constructor param?

2018-10-03 00:23 UTC, puregarlic commented on src/dal/search/index.ts
> +  private async delete(id: string) {
I'd prefer not to disable TSLint for this line, mainly because the name `delete` is a bit ambiguous. What are you deleting? It's not immediately clear.

2018-10-05 21:08 UTC, danvanhorn commented on src/dal/search/index.ts
> +    this.host = 'es-search:9200';
No reason in particular. I'm going to refactor it to use that convention but we may be deleting the `mongodb` client and just using `elasticsearch` for searching and filtering as we've discussed before.

2018-10-05 21:09 UTC, danvanhorn commented on src/dal/search/index.ts
> +  private async delete(id: string) {
It was because I was using the name `delete` for the function. I changed the name to `deleteDocument`. I also changed `exists` to `documentExists`.

2018-10-08 19:37 UTC, merged

2018-10-26 19:18 UTC, cass-osu commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/osu-cass/AP-CSE-API/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2018-10-31 22:59 UTC, cass-osu commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/osu-cass/AP-CSE-API/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: