feat(data model): adds related evidence to task model property
osu-cass/AP-CSE-API pull request #16
Opened 2018-10-01 19:07 UTC by Cleverus3rname

# Changes introduced
Updated the data model to have support for the evidence required <-> task model relationship
Added handling to the import script for this data model change

## Related issue(s):
- CSE-280

## Contributor checklist

- [x] Wrote/updated tests for introduced changes
- [ ] ~~Added new stories for created/modified components (if applicable)~~
- [ ] Updated Postman library for created/modified routes (if applicable)
- [x] Verified that there are no issues in CircleCI
- [x] Assigned yourself to the PR
- [x] Removed `WIP:` from the PR title
- [ ] Requested review from the SB Reviewers team

## Reviewer checklist

- [ ] Assigned yourself to the PR
- [ ] Read through the changes in the `Files changed` tab
- [ ] Verified that tests were written/modified
- [ ] ~~Verified that stories were written/modified (if applicable)~~
- [ ] Verified that Postman was updated (if applicable)
- [ ] Checked out the branch and tested changes locally

2018-10-03 00:49 UTC, puregarlic requested changes

2018-10-03 00:49 UTC, puregarlic commented on src/models/target/index.ts
>  // tslint:disable:no-reserved-keywords
This file needs to be formatted before it's merged. Otherwise, it looks great.

2018-10-08 19:25 UTC, danvanhorn approved these changes
I've ran everything locally and tested the changes. Good job.

2018-10-08 19:25 UTC, danvanhorn commented on src/models/target/index.ts
> +export interface IEvidence {
Good thinking adding an interface for this. we may have to update the types on the client side too so the client-side team can take advantage of them.

2018-10-08 19:26 UTC, merged

2018-10-26 19:18 UTC, cass-osu commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/osu-cass/AP-CSE-API/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2018-10-31 22:59 UTC, cass-osu commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/osu-cass/AP-CSE-API/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: